import RequestProject.VanDenEssen.Criterion

/-!
# Existence of the Van den Essen basis

This file shows that the hypotheses of the criterion are *satisfiable*: if `F` is a polynomial
automorphism with inverse `H`, then the list

`[x₁ - H₁(y), …, xₙ - Hₙ(y)]`

really is a reduced Gröbner basis of the graph ideal `I(F)` for the lexicographic elimination
order.  In particular the criterion is not vacuous, and it delivers the inverse.

Two ingredients are needed beyond what has been proved so far.

* A refinement of the order comparison: in the lexicographic order with `x > y`, **any**
  monomial involving an `x`-variable beats **every** monomial in the `y`-variables alone.
  Consequently a nonzero element of `I(F)` has a leading monomial involving some `xⱼ`
  (otherwise all of its monomials would be `y`-monomials, and `I(F) ∩ k[y] = 0`).
* The graph ideal is also generated by the "inverse" relations `xᵢ - Hᵢ(y)`.
-/

namespace VanDenEssen

open MvPolynomial

section PureY

variable {n : Nat}

/-- In the lexicographic order with the `x`-variables first, a monomial that involves some
`x`-variable is strictly larger than every monomial in the `y`-variables alone. -/
lemma lex_lt_of_pure_y {d e : Fin (2 * n) →₀ ℕ} (he : ∀ j, e (xv j) = 0)
    {j0 : Fin n} (hj0 : d (xv j0) ≠ 0) : lexOrder.toSyn e < lexOrder.toSyn d := by
  classical
  set S : Finset (Fin n) := Finset.univ.filter (fun j => d (xv j) ≠ 0) with hSdef
  have hS : S.Nonempty := ⟨j0, by simp [hSdef, hj0]⟩
  set j := S.min' hS with hjdef
  have hjS : j ∈ S := S.min'_mem hS
  have hdj : d (xv j) ≠ 0 := by
    have := hjS
    rw [hSdef, Finset.mem_filter] at this
    exact this.2
  have hmin : ∀ j' : Fin n, j' < j → d (xv j') = 0 := by
    intro j' hj'
    by_contra hc
    have hmem : j' ∈ S := by rw [hSdef, Finset.mem_filter]; exact ⟨Finset.mem_univ _, hc⟩
    exact absurd (S.min'_le j' hmem) (not_le.2 hj')
  rw [lexOrder, MonomialOrder.lex_lt_iff, Finsupp.Lex.lt_iff]
  simp only [ofLex_toLex]
  refine ⟨xv j, ?_, ?_⟩
  · intro k hk
    have hkv : k.val < j.val := by simpa using hk
    have hjn := j.isLt
    have hke : k = xv ⟨k.val, by omega⟩ := Fin.ext (by simp)
    rw [hke, he, hmin ⟨k.val, by omega⟩ (by rw [Fin.lt_def]; simpa using hkv)]
  · rw [he j]
    exact Nat.pos_of_ne_zero hdj

variable {K : Type*} [CommRing K]

/-- If the leading monomial of `p` involves no `x`-variable, then no monomial of `p` does. -/
lemma support_pure_y_of_degree_pure_y {p : MvPolynomial (Fin (2 * n)) K}
    (hp : ∀ j : Fin n, lexOrder.degree p (xv j) = 0) :
    ∀ d ∈ p.support, ∀ j : Fin n, d (xv j) = 0 := by
  intro d hd j
  by_contra hdj
  exact absurd (MonomialOrder.le_degree hd) (not_le.2 (lex_lt_of_pure_y hp hdj))

/-- The monomial `xⱼ` divides any monomial in which `xⱼ` occurs. -/
lemma single_xv_le {d : Fin (2 * n) →₀ ℕ} {j : Fin n} (hdj : d (xv j) ≠ 0) :
    Finsupp.single (xv j) 1 ≤ d := by
  rw [Finsupp.le_def]
  intro a
  rcases eq_or_ne (xv j) a with rfl | hne
  · rw [Finsupp.single_eq_same]; omega
  · rw [Finsupp.single_apply, if_neg hne]; exact Nat.zero_le _

end PureY

section Existence

variable {n : Nat} {K : Type*} [Field K]

/-- The leading monomial of a nonzero element of the graph ideal of an injective substitution
involves some `x`-variable. -/
theorem exists_degree_xv_ne_zero {F : PolyMap n K}
    (hinj : Function.Injective (aeval F : MvPolynomial (Fin n) K →ₐ[K] MvPolynomial (Fin n) K))
    {p : MvPolynomial (Fin (2 * n)) K} (hp : p ∈ graphIdeal F) (hp0 : p ≠ 0) :
    ∃ j : Fin n, lexOrder.degree p (xv j) ≠ 0 := by
  by_contra hc
  push_neg at hc
  obtain ⟨q, hq⟩ := exists_rename_yv_of_support p (support_pure_y_of_degree_pure_y hc)
  rw [← hq] at hp
  have hq0 : aeval F q = 0 := (rename_yv_mem_graphIdeal_iff F q).1 hp
  have : q = 0 := hinj (by simpa using hq0)
  rw [this, map_zero] at hq
  exact hp0 hq.symm

/-- Modulo the ideal generated by the relations `xᵢ - Hᵢ(y)`, substituting `x` into a polynomial
is the same as substituting `H(y)`. -/
lemma rename_xv_sub_rename_yv_aeval_mem (H : PolyMap n K)
    (J : Ideal (MvPolynomial (Fin (2 * n)) K))
    (hJ : ∀ i, (X (xv i) - rename yv (H i)) ∈ J) (p : MvPolynomial (Fin n) K) :
    rename xv p - rename yv (aeval H p) ∈ J := by
  induction p using MvPolynomial.induction_on with
  | C a => simp
  | add p q hp hq =>
      have : rename xv (p + q) - rename yv (aeval H (p + q))
          = (rename xv p - rename yv (aeval H p)) + (rename xv q - rename yv (aeval H q)) := by
        rw [map_add, map_add, map_add]; ring
      rw [this]
      exact Ideal.add_mem _ hp hq
  | mul_X p i hp =>
      have hsplit : rename xv (p * X i) - rename yv (aeval H (p * X i))
          = (rename xv p - rename yv (aeval H p)) * X (xv i)
            + rename yv (aeval H p) * (X (xv i) - rename yv (H i)) := by
        rw [map_mul, map_mul, map_mul, rename_X, aeval_X]
        ring
      rw [hsplit]
      exact Ideal.add_mem _ (Ideal.mul_mem_right _ _ hp) (Ideal.mul_mem_left _ _ (hJ i))

/-- **The graph ideal is also generated by the inverse relations.**
If `H` is a right inverse of `F` then `I(F) = ⟨x₁ - H₁(y), …, xₙ - Hₙ(y)⟩`. -/
theorem graphIdeal_eq_span_inverse_relations {F H : PolyMap n K} (hFH : comp F H = idMap)
    (hHF : comp H F = idMap) :
    graphIdeal F = Ideal.span (Set.range fun i : Fin n => X (xv i) - rename yv (H i)) := by
  set J : Ideal (MvPolynomial (Fin (2 * n)) K) :=
    Ideal.span (Set.range fun i : Fin n => X (xv i) - rename yv (H i)) with hJdef
  have hJmem : ∀ i, (X (xv i) - rename yv (H i)) ∈ J := fun i => Ideal.subset_span ⟨i, rfl⟩
  refine le_antisymm ?_ ?_
  · -- every generator `yⱼ - Fⱼ(x)` of `I(F)` lies in `J`
    rw [graphIdeal, Ideal.span_le]
    rintro g ⟨j, rfl⟩
    have h := rename_xv_sub_rename_yv_aeval_mem H J hJmem (F j)
    have hFj : aeval H (F j) = X j := congrFun hFH j
    rw [hFj, rename_X] at h
    have : graphGen F j = -(rename xv (F j) - X (yv j)) := by rw [graphGen]; ring
    rw [SetLike.mem_coe, this]
    exact neg_mem h
  · -- conversely each `xᵢ - Hᵢ(y)` lies in `I(F)`
    rw [hJdef, Ideal.span_le]
    rintro g ⟨i, rfl⟩
    exact (forall_X_xv_sub_mem_iff F H).2 hHF i

/-- **Existence of the Van den Essen basis.**  If `F` is a polynomial automorphism with inverse
`H`, then `[x₁ - H₁(y), …, xₙ - Hₙ(y)]` is a reduced Gröbner basis of the graph ideal `I(F)`
for the lexicographic elimination order. -/
theorem isReducedGrobnerBasis_ofFn {F H : PolyMap n K} (hFH : comp F H = idMap)
    (hHF : comp H F = idMap) :
    isReducedGrobnerBasis (List.ofFn fun i : Fin n => X (xv i) - rename yv (H i))
      (graphIdeal F) lexOrder := by
  have hinj := aeval_injective_of_comp_eq_id hFH
  have hmem : ∀ i : Fin n, (X (xv i) - rename yv (H i)) ∈ graphIdeal F :=
    (forall_X_xv_sub_mem_iff F H).2 hHF
  have hlist : ∀ g : MvPolynomial (Fin (2 * n)) K,
      g ∈ (List.ofFn fun i : Fin n => X (xv i) - rename yv (H i)) ↔
        ∃ i : Fin n, X (xv i) - rename yv (H i) = g := by
    intro _; exact List.mem_ofFn
  have hdeg : ∀ i : Fin n,
      lexOrder.degree (X (xv i) - rename yv (H i) : MvPolynomial (Fin (2 * n)) K)
        = Finsupp.single (xv i) 1 := fun i => degree_X_xv_sub_rename_yv i (H i)
  refine ⟨⟨?_, ?_⟩, ?_, ?_⟩
  · -- the list generates the graph ideal
    rw [graphIdeal_eq_span_inverse_relations hFH hHF]
    congr 1
    ext g
    rw [Set.mem_setOf_eq, hlist]
    exact ⟨fun ⟨i, hi⟩ => ⟨i, hi⟩, fun ⟨i, hi⟩ => ⟨i, hi⟩⟩
  · -- the leading monomials `xᵢ` generate the initial ideal
    intro p hp hp0
    obtain ⟨j, hj⟩ := exists_degree_xv_ne_zero hinj hp hp0
    refine ⟨X (xv j) - rename yv (H j), (hlist _).2 ⟨j, rfl⟩,
      X_xv_sub_rename_yv_ne_zero j (H j), ?_⟩
    rw [hdeg j]
    exact single_xv_le hj
  · -- each member is monic
    intro g hg
    obtain ⟨i, rfl⟩ := (hlist g).1 hg
    exact monic_X_xv_sub_rename_yv i (H i)
  · -- the basis is reduced
    intro g hg d hd h hh hne
    obtain ⟨i, rfl⟩ := (hlist g).1 hg
    obtain ⟨k, rfl⟩ := (hlist h).1 hh
    have hik : k ≠ i := by
      intro hki; exact hne (by rw [hki])
    rw [hdeg k]
    intro hle
    have h1 : (Finsupp.single (xv k) 1 : Fin (2 * n) →₀ ℕ) (xv k) ≤ d (xv k) := by
      rw [Finsupp.le_def] at hle; exact hle _
    rw [Finsupp.single_eq_same] at h1
    -- so `xₖ` occurs in the monomial `d` of `xᵢ - Hᵢ(y)`
    have hdk : d (xv k) ≠ 0 := by omega
    have hdi : d = Finsupp.single (xv i) 1 := by
      by_contra hdne
      -- otherwise `d` is a monomial of `Hᵢ(y)`, which involves no `x`-variable
      have hcoeff : coeff d (X (xv i) - rename yv (H i)) ≠ 0 := mem_support_iff.1 hd
      have hdsupp : d ∈ (rename yv (H i)).support := by
        refine mem_support_iff.2 fun hc => hcoeff ?_
        rw [coeff_sub, hc, sub_zero, coeff_X', if_neg (Ne.symm hdne)]
      exact hdk (support_rename_yv_apply_xv hdsupp k)
    rw [hdi, Finsupp.single_apply, if_neg (fun hc => hik (xv_injective hc).symm)] at hdk
    exact hdk rfl

/-- The Van den Essen basis of an automorphism is in Van den Essen shape. -/
theorem hasVanDenEssenShape_ofFn {F H : PolyMap n K} (hFH : comp F H = idMap)
    (hHF : comp H F = idMap) :
    hasVanDenEssenShape (List.ofFn fun i : Fin n => X (xv i) - rename yv (H i)) :=
  shape_of_reduced_groebner (isReducedGrobnerBasis_ofFn hFH hHF) ⟨H, hFH, hHF⟩

/-- **The criterion is non-vacuous:** every polynomial automorphism admits a reduced Gröbner
basis of its graph ideal, and that basis has Van den Essen shape. -/
theorem exists_reducedGrobnerBasis_of_isPolynomialAutomorphism {F : PolyMap n K}
    (hF : IsPolynomialAutomorphism F) :
    ∃ G : List (MvPolynomial (Fin (2 * n)) K),
      isReducedGrobnerBasis G (graphIdeal F) lexOrder ∧ hasVanDenEssenShape G := by
  obtain ⟨H, hFH, hHF⟩ := hF
  exact ⟨_, isReducedGrobnerBasis_ofFn hFH hHF, hasVanDenEssenShape_ofFn hFH hHF⟩

end Existence

end VanDenEssen
